### PR TITLE
cmd/loopd: point to testnet loop server for testnet mode

### LINKED ISSUE #20: loop out failes on testnet
When trying to use loop on testnet (loopd started with `network=testnet` option), the loop binary fails with this error:

```
pat@ubuntu:~/.lnd/data/chain/bitcoin/testnet$ loop out 1000000
Max swap fees for 1000000 loop out: 54972
CONTINUE SWAP? (y/n), expand fee detail (x): x

Max on-chain fee:                 411
Max off-chain swap routing fee:   50010
Max off-chain prepay routing fee: 422
Max swap fee:                     4129
Max no show penalty:              8258
CONTINUE SWAP? (y/n): y
[loop] rpc error: code = Unknown desc = invoice not for current active network 'testnet3'
```

Environment:
- loop version 0.0.1
- Linux ubuntu-s-2vcpu-2gb-fra1-01 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by Roasbeef**
Fixes #20.

### CODE REVIEW

File: cmd/loopd/daemon.go [hunk 1]
```diff
@@ -26,6 +26,12 @@ func daemon(config *config) error {
 	}
 	defer lnd.Close()
 
+	// If the user is targetting the testnet network, then we'll point
```
Comment (alexbosworth) [inline cmd/loopd/daemon.go]:
```suggestion
	// If the user is targeting the testnet network, then we'll point
```
