### PR TITLE
multi: base sweep fee estimate on actually used address type

### LINKED ISSUE #69: Hanging on LOOP_OUT PREIMAGE_REVEALED
Attempting to loop out a channel of loop's choosing with the following command:

```
$ loop out 331004 --addr n3j7rbY4fUd23XDEKPHVFuTkv5qU6gsSQB
```

Running loop monitor prints the following:

```
$ loop monitor
Note: offchain cost may report as 0 after loopd restart during swap
2019-07-26T16:32:22Z LOOP_OUT PREIMAGE_REVEALED 0.00331004 BTC - tb1q6pvk82ch64wcalzu6ql9dvxrgunm573wmxm0kqtjjxxs87umljtqt5rale 
```

Here are the logs from loop
```
2019-07-26 16:21:45.963 [INF] CLIENT: Offchain swap destination: 0223acffd7f363b4591ce860eda870fea352e981212d8a25e96a0ebea37faae288                                                           
2019-07-26 16:21:49.738 [INF] LOOPD: Loop out request received                                                                                                                                
2019-07-26 16:21:49.738 [INF] CLIENT: LoopOut 0.00331004 BTC to n3j7rbY4fUd23XDEKPHVFuTkv5qU6gsSQB (channel: <nil>)                                                                           
2019-07-26 16:21:49.754 [INF] CLIENT: Initiating swap request at height 1571110                                                                                                               
2019-07-26 16:21:50.502 [INF] CLIENT: 014e40 Htlc address: tb1q6pvk82ch64wcalzu6ql9dvxrgunm573wmxm0kqtjjxxs87umljtqt5rale                                                                     
2019-07-26 16:21:50.508 [INF] CLIENT: 014e40 state Initiated                                                                                                                                  
2019-07-26 16:21:50.508 [INF] CLIENT: 014e40 Sending swap payment lntb3310100n1pwnk2y7pp5q98yq20ff70mnqlqm8xsvtld5t9va5r9yxf4y36eppnn5wpf7ywqdq8wdmkzuqcqzxgxq97zvuqg3dr7zamxvmndsjj4559fvt5my
tv25fwuj2mdw2gmqq76xrztlnpar0leu09p7q4myva0u8q3vq2q884gsmfmqahx96nexkyqrn0fvcpp6fcxh                                                                                                          
2019-07-26 16:21:50.508 [INF] CLIENT: 014e40 Sending prepayment lntb13370n1pwnk2y7pp54qz0zckfqk4pfrzx8k00k9g7hex0suk4xfv2nwn7knyaqnhx4feqdq2wpex2urp0ycqzxgxq97zvuq0x3hs743qkakucllxh3arvv3cyt
n588j6pxr0nzn8rc0u4qegqq42k78fkgkrz7jdayqkcdg68vt6ehnjdemkhnh6x7aszwsaghsf2qps2vump                                                                                                           
2019-07-26 16:21:50.508 [INF] CLIENT: 014e40 Register conf ntfn for swap script on chain (hh=1571110)                                                                                         
2019-07-26 16:21:50.509 [INF] CLIENT: 014e40 Checking preimage reveal height 1571190 exceeded (height 1571110)                                                                                
2019-07-26 16:21:50.509 [INF] CLIENT: 014e40 Waiting for either htlc on-chain confirmation or  off-chain payment failure                                                                      
2019-07-26 16:21:57.649 [INF] LNDCLIENT: Payment a804f162c905aa148c463d9efb151ebe4cf872d53258a9ba7eb4c9d04ee6aa72 completed                                                                   
2019-07-26 16:22:15.502 [INF] LOOPD: Monitor request received                                                                                                                                 
2019-07-26 16:32:12.953 [INF] CLIENT: Received block 1571111                                                                                                                                  
2019-07-26 16:32:12.953 [INF] CLIENT: 014e40 Checking preimage reveal height 1571190 exceeded (height 1571111)                                                                                
2019-07-26 16:32:12.953 [INF] CLIENT: 014e40 Swap script confirmed on chain                                                                                                                   
2019-07-26 16:32:12.954 [INF] CLIENT: 014e40 Htlc tx cd6d9bc5a309d7a4e7c0b2bee6dce7c021b7c9691d619c7fdd5643cf2dd43870 at height 1571111                                                       
2019-07-26 16:32:12.954 [INF] CLIENT: 014e40 Htlc value: 0.00331004 BTC                                                                                                                       
2019-07-26 16:32:22.965 [INF] CLIENT: 014e40 state PreimageRevealed
2019-07-26 16:32:22.965 [INF] CLIENT: 014e40 Sweep on chain HTLC to address n3j7rbY4fUd23XDEKPHVFuTkv5qU6gsSQB with fee 0.00000138 BTC (tx d4cf9b15e4de998b66dca98d72f6d8969a291ab453c06ded5b5e88f7fd24af92)
2019-07-26 16:32:22.986 [WRN] CLIENT: 014e40 Publish sweep: rpc error: code = Unknown desc = -26: min relay fee not met, 138 < 139 (code 66)                                                 
2019-07-26 16:52:27.069 [INF] CLIENT: 014e40 Sweep on chain HTLC to address n3j7rbY4fUd23XDEKPHVFuTkv5qU6gsSQB with fee 0.00000138 BTC (tx 338d76463540d4b98ee2a3bc740bbcd07c5226f2c4c44aa17151223f2632dca3)
2019-07-26 16:52:27.090 [WRN] CLIENT: 014e40 Publish sweep: rpc error: code = Unknown desc = -26: min relay fee not met, 138 < 139 (code 66)                                                 
2019-07-26 17:12:40.805 [INF] CLIENT: 014e40 Sweep on chain HTLC to address n3j7rbY4fUd23XDEKPHVFuTkv5qU6gsSQB with fee 0.00000138 BTC (tx 38d8924d3ec9300992efffd1752eb37f67c0edb387959b7e735d7d378434e90d)
2019-07-26 17:12:40.823 [WRN] CLIENT: 014e40 Publish sweep: rpc error: code = Unknown desc = -26: min relay fee not met, 138 < 139 (code 66)                                                 
2019-07-26 17:26:08.237 [INF] CLIENT: 014e40 Sweep on chain HTLC to address n3j7rbY4fUd23XDEKPHVFuTkv5qU6gsSQB with fee 0.00000138 BTC (tx c319b6cb6203686bb4d1d68ed782fc0841183051b0920c8706ccfc1d855e7906)
2019-07-26 17:26:08.251 [WRN] CLIENT: 014e40 Publish sweep: rpc error: code = Unknown desc = -26: min relay fee not met, 138 < 139 (code 66)                                                 
2019-07-26 17:37:14.333 [INF] CLIENT: 014e40 Sweep on chain HTLC to address n3j7rbY4fUd23XDEKPHVFuTkv5qU6gsSQB with fee 0.00000138 BTC (tx 3eba3baba59f5fab6e2c4e1e474bf6343e2bdc3962f5b953557e4702f5e75ba2)
2019-07-26 17:37:14.346 [WRN] CLIENT: 014e40 Publish sweep: rpc error: code = Unknown desc = -26: min relay fee not met, 138 < 139 (code 66)                                                 
2019-07-26 17:41:41.732 [INF] CLIENT: 014e40 Sweep on chain HTLC to address n3j7rbY4fUd23XDEKPHVFuTkv5qU6gsSQB with fee 0.00000138 BTC (tx 4be6206c4a6e18c457d4ed7e0024474778b4ad196822e5a75d05ef13f3be7c6f)
2019-07-26 17:41:41.746 [WRN] CLIENT: 014e40 Publish sweep: rpc error: code = Unknown desc = -26: min relay fee not met, 138 < 139 (code 66)                                                 
2019-07-26 17:43:20.349 [INF] CLIENT: 014e40 Sweep on chain HTLC to address n3j7rbY4fUd23XDEKPHVFuTkv5qU6gsSQB with fee 0.00000138 BTC (tx 43770da0d6e74727de544edb72d11c11f21d5aff4e6cd2d35cf8a85e3da7a66b)
2019-07-26 17:43:20.361 [WRN] CLIENT: 014e40 Publish sweep: rpc error: code = Unknown desc = -26: min relay fee not met, 138 < 139 (code 66)
2019-07-26 17:44:42.287 [INF] CLIENT: 014e40 Sweep on chain HTLC to address n3j7rbY4fUd23XDEKPHVFuTkv5qU6gsSQB with fee 0.00000138 BTC (tx 1f798533b0062ad3f3ad5b77c4ceff8dae04c2040b796da34d7
885f3b61bf68b)
2019-07-26 17:44:42.302 [WRN] CLIENT: 014e40 Publish sweep: rpc error: code = Unknown desc = -26: min relay fee not met, 138 < 139 (code 66)
2019-07-26 17:55:13.572 [INF] CLIENT: 014e40 Sweep on chain HTLC to address n3j7rbY4fUd23XDEKPHVFuTkv5qU6gsSQB with fee 0.00000138 BTC (tx 5e1f42d200196d007c3dc456bed70ba6a98f90ab31cd0153dc0
ac58fcdc7e7cd)
2019-07-26 17:55:13.588 [WRN] CLIENT: 014e40 Publish sweep: rpc error: code = Unknown desc = -26: min relay fee not met, 138 < 139 (code 66)
2019-07-26 18:14:45.265 [INF] CLIENT: 014e40 Sweep on chain HTLC to address n3j7rbY4fUd23XDEKPHVFuTkv5qU6gsSQB with fee 0.00000138 BTC (tx 55c1f85ffd9d1262a547b3a5e2a092545688a344f1e244c820b
5caedf7512e6f)
2019-07-26 18:14:45.283 [WRN] CLIENT: 014e40 Publish sweep: rpc error: code = Unknown desc = -26: min relay fee not met, 138 < 139 (code 66)
```

It appears like there is some kind of fee issue presenting, advice on how to proceed?

### PR DESCRIPTION
**Pull request by joostjager**
Fixes #69

### CODE REVIEW

File: sweep/sweeper.go [hunk 1]
```diff
@@ -102,7 +102,19 @@ func (s *Sweeper) GetSweepFee(ctx context.Context,
...
 	var weightEstimate input.TxWeightEstimator
-	weightEstimate.AddP2WKHOutput()
+	switch destAddr.(type) {
+	case *btcutil.AddressWitnessScriptHash:
+		weightEstimate.AddP2WSHOutput()
+	case *btcutil.AddressWitnessPubKeyHash:
+		weightEstimate.AddP2WKHOutput()
+	case *btcutil.AddressScriptHash:
+		weightEstimate.AddP2SHOutput()
+	case *btcutil.AddressPubKeyHash:
```
Comment (wpaulino) [inline sweep/sweeper.go]: Nit: I don't think we support these addresses so can be removed?

Comment (joostjager) [reply sweep/sweeper.go]: This address can be specified externally, on the `loop` command line.

File: loopout.go [hunk 2]
```diff
@@ -31,7 +31,7 @@ var (
 	// confirmation target.
 	//
 	// TODO(wilmer): tune?
-	DefaultSweepConfTargetDelta int32 = DefaultSweepConfTarget * 2
+	DefaultSweepConfTargetDelta = DefaultSweepConfTarget * 2
```
Comment (halseth) [inline loopout.go]: Shouldn't all these be `const` really?

Comment (joostjager) [reply loopout.go]: Yes, they could be const. There are some in `loopin.go` too. I just fixed this because my IDE complained. Will leave further changes out of this PR.
