### PR TITLE
loopout: allow multi-loop

### LINKED ISSUE #117: Payment already in flight?
I tried to perform two loop outs yesterday using v0.3.0-alpha. They both were performed without the --fast flag. Loopd was terminated approximately an hr or so after initialized. The logs state payments failed, but the ```loop monitor``` command keeps states transactions are still labeled initiated and not failed. It keeps stating payment still in flight for the past few hours.

```
2019-11-28 09:59:59.362 [INF] LOOP: LoopOut 0.02 BTC to xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx (channel: <nil>)
2019-11-28 09:59:59.689 [INF] LOOP: Initiating swap request at height 605777
2019-11-28 09:59:59.882 [INF] LOOP: 000000 Htlc address: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2019-11-28 09:59:59.899 [INF] LOOP: 000000 state Initiated
2019-11-28 09:59:59.900 [INF] LOOP: 000000 Sending swap payment xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx$
2019-11-28 09:59:59.900 [INF] LOOP: 000000 Sending prepayment xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx$
2019-11-28 09:59:59.901 [INF] LOOP: 000000 Register conf ntfn for swap script on chain (hh=605777)
2019-11-28 09:59:59.905 [INF] LOOP: 000000 Checking preimage reveal height 605857 exceeded (height 605777)
2019-11-28 09:59:59.905 [INF] LOOP: 000000 Waiting for either htlc on-chain confirmation or  off-chain payment failure
2019-11-28 10:00:05.808 [INF] LOOPD: Monitor request received
2019-11-28 10:01:16.718 [WRN] LNDC: Payment xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx failed: payment attempt not completed before timeout
2019-11-28 10:01:16.718 [INF] LOOP: 000000 Failed swap payment: payment attempt not completed before timeout
2019-11-28 10:01:16.718 [INF] LOOP: 000000 Wait for server pulling off-chain payment(s)
2019-11-28 11:06:24.277 [INF] LOOPD: Monitor request received
2019-11-28 11:41:00.430 [INF] LOOPD: Monitor request received
2019-11-28 13:44:08.224 [INF] LOOPD: Monitor request received
2019-11-28 13:45:07.356 [INF] LOOPD: Received SIGINT (Ctrl+C).
2019-11-28 13:45:07.380 [ERR] LOOP: 000000 Swap error: context canceled
2019-11-28 13:45:07.373 [INF] LOOP: Swap client terminating
2019-11-28 13:45:07.380 [INF] LOOP: 000000 state FailTemporary
2019-11-28 13:45:07.397 [INF] LOOP: Swap client terminated
2019-11-28 13:45:07.397 [INF] LOOPD: Swap client stopped
2019-11-28 13:45:07.397 [INF] LOOPD: Stopping gRPC server
```
```
2019-11-28 23:20:39.223 [INF] LOOP: 000000 Register conf ntfn for swap script on chain (hh=605816)
2019-11-28 23:20:39.224 [INF] LOOP: 000000 Checking preimage reveal height 605896 exceeded (height 605866)
2019-11-28 23:20:39.224 [INF] LOOP: 000000 Waiting for either htlc on-chain confirmation or  off-chain payment failure
2019-11-28 23:20:39.221 [INF] LOOP: 000000 Checking preimage reveal height 605857 exceeded (height 605866)
2019-11-28 23:20:39.224 [INF] LOOP: 000000 Max preimage reveal height 605857 exceeded (height 605866)
2019-11-28 23:20:39.224 [INF] LOOP: 000000 Wait for server pulling off-chain payment(s)
```

```
2019-11-28 14:02:22.012 [INF] LOOPD: Loop out request received
2019-11-28 14:02:22.303 [INF] LOOP: LoopOut 0.01 BTC to xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx (channel: <nil>)
2019-11-28 14:02:22.344 [INF] LNDC: Payment xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx already in flight
2019-11-28 14:02:22.389 [INF] LOOP: Initiating swap request at height 605816
2019-11-28 14:02:22.556 [INF] LOOP: 000001 Htlc address: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2019-11-28 14:02:22.597 [INF] LOOP: 000001 state Initiated
2019-11-28 14:02:22.598 [INF] LOOP: 000001 Sending swap payment xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx$
2019-11-28 14:02:22.598 [INF] LOOP: 000001 Sending prepayment xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx$
2019-11-28 14:02:22.598 [INF] LOOP: 000001 Register conf ntfn for swap script on chain (hh=605816)
2019-11-28 14:02:22.598 [INF] LOOP: 000001 Checking preimage reveal height 605896 exceeded (height 605816)
2019-11-28 14:02:22.599 [INF] LOOP: 000001 Waiting for either htlc on-chain confirmation or  off-chain payment failure
2019-11-28 14:12:27.465 [WRN] LNDC: Payment xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx failed: IncorrectOrUnknownPaymentDetails(amt=1000163000 mSAT, height=605816)
2019-11-28 14:12:27.465 [INF] LOOP: 000001 Failed swap payment: IncorrectOrUnknownPaymentDetails(amt=1000163000 mSAT, height=605816)
2019-11-28 14:12:27.478 [INF] LOOP: 000001 Wait for server pulling off-chain payment(s)
```

```
2019-11-29 08:07:31.095 [INF] LOOPD: RPC server listening on 127.0.0.1:11010
2019-11-29 08:07:31.105 [INF] LOOPD: REST proxy listening on 127.0.0.1:8081
2019-11-29 08:07:31.179 [INF] LOOP: Connected to lnd node XXXXXX with pubkey xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2019-11-29 08:07:31.181 [INF] LOOP: Wait for first block ntfn
2019-11-29 08:07:31.182 [INF] LOOP: Resuming loop out swap xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2019-11-29 08:07:31.184 [INF] LOOP: 000000 Htlc address: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2019-11-29 08:07:31.212 [INF] LOOP: Starting event loop at height 605916
2019-11-29 08:07:31.213 [INF] LOOP: Resuming loop out swap xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2019-11-29 08:07:31.213 [INF] LOOP: 000001 Htlc address: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2019-11-29 08:07:31.217 [INF] LOOP: 000000 state Initiated
2019-11-29 08:07:31.217 [INF] LOOP: 000001 state Initiated
2019-11-29 08:07:31.218 [INF] LOOP: 000001 Sending swap payment xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx $
2019-11-29 08:07:31.218 [INF] LOOP: 000001 Sending prepayment xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx $
2019-11-29 08:07:31.221 [INF] LOOP: 000001 Register conf ntfn for swap script on chain (hh=605816)
2019-11-29 08:07:31.218 [INF] LOOP: 000000 Sending swap payment xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx$
2019-11-29 08:07:31.222 [INF] LOOP: 000000 Sending prepayment xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx$
2019-11-29 08:07:31.222 [INF] LOOP: 000000 Register conf ntfn for swap script on chain (hh=605777)
2019-11-29 08:07:31.223 [INF] LOOP: 000000 Checking preimage reveal height 605857 exceeded (height 605916)
2019-11-29 08:07:31.223 [INF] LOOP: 000000 Max preimage reveal height 605857 exceeded (height 605916)
2019-11-29 08:07:31.224 [INF] LOOP: 000000 Wait for server pulling off-chain payment(s)
2019-11-29 08:07:31.230 [INF] LOOP: 000001 Checking preimage reveal height 605896 exceeded (height 605916)
2019-11-29 08:07:31.231 [INF] LOOP: 000001 Max preimage reveal height 605896 exceeded (height 605916)
2019-11-29 08:07:31.232 [INF] LOOP: 000001 Wait for server pulling off-chain payment(s)
2019-11-29 08:07:31.667 [INF] LNDC: Payment xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx already in flight
2019-11-29 08:07:31.668 [INF] LNDC: Payment xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx already in flight
2019-11-29 08:07:34.807 [INF] LNDC: Payment xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx already in flight
```

### PR DESCRIPTION
**Pull request by joostjager**
This PR moves over the loop out code to use `routerrpc` for sending payments. Only with `routerrpc` it is possible to make payments consisting of multiple shards.

The maximum number of shards is fixed to `5` in this PR. In a follow-up, this can be refined further.

Fixes #117

### CODE REVIEW

File: lndclient/router_client.go [hunk 1]
```diff
@@ -81,6 +93,10 @@ type SendPaymentRequest struct {
 	// LastHopPubkey is the pubkey of the last hop of the route taken
 	// for this payment. If empty, any hop may be used.
 	LastHopPubkey *route.Vertex
+
+	// The maximum number of partial payments that may be use to complete
```
Comment (guggero) [inline lndclient/router_client.go:97]: nit: s/use/used/

File: loopout.go [hunk 2]
```diff
@@ -384,19 +393,125 @@ func (s *loopOutSwap) persistState(ctx context.Context) error {
...
+
+	// Extract hash from payment request. Unfortunately the request
+	// components aren't available directly.
+	chainParams := s.lnd.ChainParams
+	hash, _, err := swap.DecodeInvoice(
+		chainParams, invoice,
+	)
+	if err != nil {
+		select {
+		case resultChan <- lndclient.PaymentResult{
```
Comment (guggero) [inline loopout.go:424]: This tries to send to an unbuffered channel that nobody is listening on yet. I don't think this will ever complete. The channel must either be buffered (then the select on `ctx.Done()` can be removed) or the whole send must be done in a subroutine.

File: lndclient/router_client.go (hunk 1 above)
Comment (joostjager) [reply lndclient/router_client.go:97]: fixed

File: loopout.go (hunk 2 above)
Comment (joostjager) [reply loopout.go:424]: Good catch, moved into goroutine

**Comment by joostjager** [comment]
To do: add check against new version api to ensure 0.10

File: lndclient/router_client.go [hunk 3]
```diff
@@ -34,10 +34,22 @@ type RouterClient interface {
...
+	Fee           lnwire.MilliSatoshi
+	Value         lnwire.MilliSatoshi
+	InFlightAmt   lnwire.MilliSatoshi
+	InFlightHtlcs int
+}
+
+func (p PaymentStatus) String() string {
+	text := fmt.Sprintf("state=%v", p.State)
+	if p.State == lnrpc.Payment_IN_FLIGHT {
+		text += fmt.Sprintf(", inflight_htlcs=%v, inflight_amt=%v",
```
Comment (carlaKC) [inline lndclient/router_client.go:48]: really nice watching your multi loop with these 👌
