### PR TITLE
loopd: verify loop out amount

### LINKED ISSUE #104: check amount is valid for loop out
if I requesting an amount above my outbound capacity, loop out will still proceed and fail the payment will "failed: unable to find a path to destination"

loop should check that the amount requested is equal or below my spending balance.

### PR DESCRIPTION
**Pull request by ellemouton**
This commit adds validation that checks if the loop out amount specified can
be satisfied given the nodes current channel balances. 

The total capacity is calculated as either the sum of the local balances of all active channels if no outgoing channel set is specified. Or if a set is specified then the total capacity is the sum of the local balances active channels in the specified set.

Fixes #104

### CODE REVIEW

**Review by carlaKC — COMMENTED** [review]
Thanks for another well tested improvement to our validation @ellemouton 🙌 Just some style nits from me that I think will improve readability a bit.

Tested for unrestricted swaps and a specific chanset and goods are as advertised! 

```
channel balance too low for loop out amount: Requested swap amount of 100000 sats along with the maximum routing fee of 2010 sats is more than the available outgoing capacity of 10950 sats
```

**Comment by ellemouton** [comment]
Thanks for the review @carlaKC 🚀  updated 👍

File: loopd/swapclient_server.go [hunk 1]
```diff
@@ -992,9 +1002,50 @@ func validateLoopOutRequest(chainParams *chaincfg.Params, confTarget int32,
...
+		if unlimitedChannels || outgoingChanSetMap[c.ChannelID] {
+			availabeBalance += c.LocalBalance
+		}
+	}
+
+	// Determine if the total outgoing capacity of the channel set is
+	// enough to satisfy the loop amount and the maximum possible
+	// routing fees that could be charged.
+	if req.Amt+req.MaxSwapRoutingFee >
+		int64(availabeBalance.ToUnit(btcutil.AmountSatoshi)) {
```
Comment (carlaKC) [inline loopd/swapclient_server.go:1040]: Could still be a bit simpler: 
```
requiredBalance := btcutil.Amount(req.Amt + req.MaxSwapRoutingFee)
if requiredBalance > availabeBalance{
  ...
}
```

**Review by carlaKC — APPROVED** [review]
Looks good!

File: loopd/swapclient_server.go (hunk 1 above)
Comment (ellemouton) [reply loopd/swapclient_server.go:1040]: oops sorry. I did update that but must have undone it by accident. Will update asap

File: loopd/swapclient_server.go [hunk 2]
```diff
@@ -992,9 +1002,50 @@ func validateLoopOutRequest(chainParams *chaincfg.Params, confTarget int32,
...
+		if unlimitedChannels || outgoingChanSetMap[c.ChannelID] {
+			availabeBalance += c.LocalBalance
+		}
+	}
+
+	// Determine if the total outgoing capacity of the channel set is
+	// enough to satisfy the loop amount and the maximum possible
+	// routing fees that could be charged.
+	requiredBalance := btcutil.Amount(req.Amt + req.MaxSwapRoutingFee)
+	if requiredBalance > availabeBalance {
```
Comment (bhandras) [inline loopd/swapclient_server.go:1040]: Note that the balance check is slightly more complicated than this. We do MPP payments when looping out and MPP (in LND) splits equally. So really we should check splitting up to the number of channels and then see if any split satisfies the required balance condition. This will also work if only one channel has enough balance for the payment or if we split maximally.

**Review by bhandras — CHANGES_REQUESTED** [review]
Great work @ellemouton. My only comment is that due to how MPP works balance check is a bit more complicated (although very easy to fix).

File: loopd/swapclient_server.go (hunk 2 above)
Comment (bhandras) [reply loopd/swapclient_server.go:1040]: Also when implementing, imo it's a good idea to separate this into it's own function and then it's easier to drop once MPP splits more intelligently.

Comment (ellemouton) [reply loopd/swapclient_server.go:1040]: ok cool! Didn't know this at all. Will update 👍

File: config.go [hunk 3]
```diff
@@ -15,4 +15,5 @@ type clientConfig struct {
 	Store             loopdb.SwapStore
 	LsatStore         lsat.Store
 	CreateExpiryTimer func(expiry time.Duration) <-chan time.Time
+	LoopOutMaxParts   uint32
```
Comment (ellemouton) [inline config.go:18]: im not sure if this is the right place to put this. Let me know if there is a better way to give the swapclient_server access to this value

**Review by bhandras — CHANGES_REQUESTED** [review]
Almost there, splitting algo needs a little correction.

File: loopd/swapclient_server.go [hunk 4]
```diff
@@ -992,9 +1003,73 @@ func validateLoopOutRequest(chainParams *chaincfg.Params, confTarget int32,
...
+func isRoutable(channels []lndclient.ChannelInfo, amt btcutil.Amount,
+	maxParts uint32) bool {
+
+	var parts uint32
+	for parts = 1; parts <= maxParts; parts++ {
+		minHTLC := amt.MulF64(1 / float64(parts))
+
+		var totalRoutableParts uint32
+		for _, c := range channels {
+			routableParts := (c.LocalBalance / minHTLC).ToUnit(btcutil.AmountSatoshi)
```
[the remark this answers is not in the document]
Comment (ellemouton) [reply loopd/swapclient_server.go:1065]: Thanks so much for taking the time to create the example! Very very helpful. Yeah I didn't quite grasp the splitting in half logic before but I understand now 👍  
(The only thing is, I think line 38 should be `split /= 2` right? Otherwise an infinite loop can occur)

**Comment by ellemouton** [comment]
Cool, I updated the algorithm @bhandras. Thanks again for clarifying 😊   The only thing I left out was the minAmt per shard because this amount can only be retrieved from LND using `DefaultShardMinAmt` and even then it could be incorrect cause the user may overwrite the default value. So im wondering if it is ok to assume that minLoopAmt/maxParts will pretty much never be < shardMinAmt since this is a best effort check?

File: loopd/swapclient_server.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (bhandras) [reply loopd/swapclient_server.go]: Yes indeed, that was a mistake, I didn't test it well enough :)

**Comment by bhandras** [comment]
> Cool, I updated the algorithm @bhandras. Thanks again for clarifying blush The only thing I left out was the minAmt per shard because this amount can only be retrieved from LND using `DefaultShardMinAmt` and even then it could be incorrect cause the user may overwrite the default value. So im wondering if it is ok to assume that minLoopAmt/maxParts will pretty much never be < shardMinAmt since this is a best effort check?

Yes it's always best effort since LND does actual path finding in the splitting algo (factoring in fees too), so there's no point in being super strict. More or less having an idea that a split is possibly valid is good enough imo.

**Review by bhandras — APPROVED** [review]
LGTM, thanks @ellemouton :1st_place_medal:

**Comment by carlaKC** [comment]
Very nice, tACK @ 65fe06c!
